services:
  database:
    image: surrealdb/surrealdb:latest
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --allow-guests
      - --auth
      - --log
      - $DB_LOG_LEVEL
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:/db/surreal.db
    volumes:
      - ./db:/db
    ports:
      - 8000:8000

# volumes:
#   db:
#     name: db