services:
  database:
    container_name: database
    restart: unless-stopped
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --allow-guests
      - --auth
      - --log
      - $DB_LOG_LEVEL
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:/db/surreal.db
    volumes:
      - ./db:/db
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    depends_on:
      - caddy
  caddy:
    container_name: caddy2
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
      - '777:777'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy2_data:/data
      - caddy2_config:/config

volumes:
  caddy2_data:
    name: caddy2_data
  caddy2_config:
    name: caddy2_config
  db:
    name: db